#!/bin/bash

echo "Change hostname in the listener.ora"
# Update HOST with actual value, uniquely generated by Docker on each start
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/listener.ora
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/tnsnames.ora

pmon=`ps -ef | grep pmon_$ORACLE_SID | grep -v grep`

echo "Start the listener and database"
/etc/init.d/oracle-xe start

echo "just to be sure, start the listener again"
#su oracle -c "export ORAENV_ASK=NO;export ORACLE_SID=orcl;source oraenv;/oracle/product/12.1/db/bin/lsnrctl start"
#setting environment XE SqlPlus - http://www.davidghedini.com/pg/entry/install_oracle_11g_xe_on
#cd /u01/app/oracle/product/11.2.0/xe/bin 
#. ./oracle_env.sh

echo "Done"

echo "Show all ora processes, should see listener and ora db processes"

ps -ef | grep -i ora